### PR TITLE
disable CDC auto-flush

### PR DESCRIPTION
**Pull request by tlyu**
There are too many race conditions lurking to be running an auto-flush from inside the SOF ISR handler.

### CODE REVIEW

**Comment by obra** [comment]
What are the repercussions of this one?

**Comment by tlyu** [comment]
The existing auto-flush in the FocusSerial should take care of any flushing at the ends of Focus replies. There might need to be an explicit flush added to the write delays in Focus, assuming we want to keep them. I've been running on macOS for quite some time without the delays, without issues, for what it's worth.

**Comment by obra** [comment]
Is there a path toward a decent implementation of autoflush? (That would match what Arduino does by default on other platforms)

**Comment by tlyu** [comment]
> Is there a path toward a decent implementation of autoflush? (That would match what Arduino does by default on other platforms)

Not sure yet. Maybe I can make it do an abbreviated flush where it doesn't try to spin (and run a poorly reimplemented subset of the ISR) if there's a write queued on the peripheral.

Incidentally, I think I just found a similar bug in the AVR Arduino core where it isn't locking around the setting the current endpoint in `USB_Flush`, so calling `Serial.flush` could race with an ISR execution. (The ISR calls `USB_Flush`, as does `Serial.flush` in the CDC code, but the former runs with interrupts blocked, and the latter does not.)

**Pull request merged**
