### PR TITLE
don't corrupt backup_status in usbd_int_suspend

### PR DESCRIPTION
**Pull request by tlyu**
The suspend interrupt can fire while already suspended in a remote wakeup scenario, corrupting `backup_status` and rendering the device unresponsive after a remote wakeup. Check whether `cur_status` is already `USBD_SUSPENDED` before saving it in `backup_status`.

### CODE REVIEW

**Comment by tlyu** [comment]
We should probably submit this upstream. I'm not sure if this level of explanation is sufficient for the vendor low-level firmware maintainers to accept. I can probably provide more detailed analysis if necessary.

Note that the example `Examples/USBD/standard_hid_keyboard` in the vendor's firmware package contains a workaround for this bug, but it's not documented.

**Comment by tlyu** [comment]
Realized that the workaround was in the same repo, so went ahead and pushed a commit to remove the workaround.

**Comment by obra** [comment]
(Is it time to merge this?)

**Comment by tlyu** [comment]
> (Is it time to merge this?)

Yeah, let's go ahead and merge this. For some reason I thought the workaround and the fix were in different repos.

**Comment by obra** [comment]
merged

**Pull request merged**
